# Generated by Django 5.0.14 on 2026-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('direct_key__isnull', False), ('type', 'direct')), models.Q(('direct_key__isnull', True), ('type', 'group')), _connector='OR'), name='room_direct_key_matches_type'),
        ),
    ]
