"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DJANGO_DEBUG=(bool , False),
    DJANGO_ALLOWED_HOSTS=(list,["localhost" , "127.0.0.1"]),
    DB_PORT=(int, 3306),
    SERVICE_NAME=(str,"chat-service"),
    SERVICE_PORT=(int,8001),
)

environ.Env.read_env(BASE_DIR / ".env")




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS")
SERVICE_NAME = env("SERVICE_NAME")
SERVICE_PORT = env("SERVICE_PORT")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #third party 
    "rest_framework",

    # local
    "chat.apps.ChatConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "CONN_MAX_AGE": 60,
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# ---------------------------------------------------------------------------
# Auth Service gRPC dependency
# ---------------------------------------------------------------------------

AUTH_GRPC_HOST = env("AUTH_GRPC_HOST")
AUTH_GRPC_PORT = env.int("AUTH_GRPC_PORT")
AUTH_GRPC_TARGET = f"{AUTH_GRPC_HOST}:{AUTH_GRPC_PORT}"

AUTH_GRPC_TIMEOUT_SECONDS = env.float(
    "AUTH_GRPC_TIMEOUT_SECONDS",
    default=2.0,
)

AUTH_GRPC_MAX_RETRIES = env.int(
    "AUTH_GRPC_MAX_RETRIES",
    default=2,
)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Logging (Phase 3, Step 65). Placeholder; Phase 11 replaces it.
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "loggers": {
        # Named explicitly rather than configuring the root logger, so DEBUG
        # here does not also turn on SQL echo and grpc's internal logging.
        # propagate stays True so pytest's caplog still sees these records.
        "chat": {"handlers": ["console"], "level": "DEBUG" if DEBUG else "INFO"},
    },
}


# ---------------------------------------------------------------------------
# Django REST Framework (Phase 4, Step 75)
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    # Exactly one authenticator. SessionAuthentication and BasicAuthentication
    # are deliberately absent: they would be a second path to "authenticated"
    # that never asks Auth Service. With SessionAuthentication first, a failed
    # login would also come back as 403 instead of 401.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "chat.authn.authentication.ChatJWTAuthentication",
    ],
    # Secure by default: an endpoint is protected unless it opts out with
    # permission_classes = [AllowAny] (only the health endpoints should).
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Chat has no users; don't build Django's AnonymousUser for anonymous calls.
    "UNAUTHENTICATED_USER": None,
    "UNAUTHENTICATED_TOKEN": None,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}
