syntax = "proto3";
package auth;

service AuthService {
  rpc ValidateToken (TokenRequest) returns (TokenValidationResponse);
  rpc GetPermissions (TokenRequest) returns (PermissionsResponse);
}

message TokenRequest {
  string access_token = 1;
}

message TokenValidationResponse {
  bool active = 1;
  string user_id = 2;
  repeated string roles = 3;
  repeated string permissions = 4;
}

message PermissionsResponse {
  string user_id = 1;
  repeated string roles = 2;
  repeated string permissions = 3;
}